ARG DOCKERHUB_RUST_VERSION

FROM $DOCKERHUB_RUST_VERSION AS builder

# Declare ARG to make it available in this build stage
ARG STELLAR_CLI_CRATE_VERSION

WORKDIR /soroban-tools
COPY . .

run apt update && apt install -y libdbus-1-dev libudev-dev
RUN rustup show active-toolchain || rustup toolchain install
run if [ ! -z "$STELLAR_CLI_CRATE_VERSION" ]; then \
		cargo install \
		--config net.git-fetch-with-cli=true \
		--config build.jobs=6 -f --locked stellar-cli \
		--version "$STELLAR_CLI_CRATE_VERSION"; \
	else \
		make install_rust; \
	fi	
