#! /usr/bin/env bash
set -e

if [ ! -z "$SOROBAN_CLI_CRATE_VERSION" ]; then 
  cargo install --config net.git-fetch-with-cli=true --config build.jobs=6 -f --locked soroban-cli --version "$SOROBAN_CLI_SOURCE_FOLDER"
else 
  git clone -q https://github.com/stellar/soroban-tools.git
  pushd soroban-tools
  git fetch origin "$SOROBAN_CLI_GIT_REF" && git checkout FETCH_HEAD
  make install_rust
  popd
fi		
