#! /usr/bin/env bash
set -e
set -o pipefail

# the versions of software that tests will use
SOROBAN_EXAMPLES_GIT_HASH="main"
SOROBAN_EXAMPLES_REPO_URL="https://github.com/stellar/soroban-examples.git"
DEBUG_MODE=

# the target network under test
TARGET_NETWORK=
TARGET_NETWORK_PASSPHRASE="Standalone Network ; February 2017"
TARGET_NETWORK_SECRET_KEY="SC5O7VZUXDJ6JBDSZ74DSERXL7W3Y5LTOAMRF7RQRL3TAGAPS7LUVG3L"
TARGET_NETWORK_PUBLIC_KEY="GBZXN7PIRZGNMHGA7MUUUF4GWPY5AYPV6LY4UV2GL6VJGIQRXFDNMADI"
TARGET_NETWORK_RPC_URL=
LOG_FILE=/var/log/system-test.log

# example filter for all combos of one scenario outline: ^TestDappDevelop$/^DApp developer compiles, deploys and invokes a contract.*$
# each row in example data for a scenario outline is postfixed with '#01', '#02', example:
# TestDappDevelop/DApp developer compiles, deploys and invokes a contract#01
TEST_FILTER=""
VERBOSE_OUTPUT=false
CANCELLED=false

function print_screen_output() {
  echo "$1" | tee -a $LOG_FILE
}

print_screen_output "Starting system test ..." 

trap printout SIGINT
printout() {
  echo "Cancelling and exit."
  exit
}

trap finish EXIT
function finish {
  if [ $? -ne 0 ]; then
    echo "" >&2
    echo "" >&2
    echo "dumping $LOG_FILE ..." >&2
    echo "" >&2
    echo "" >&2
    cat $LOG_FILE >&2
  fi  
  CANCELLED=true
  if [ "$DEBUG_MODE" = "true" ]; then
      print_screen_output "** DEBUG MODE Enabled **"
      read -p 'Debug mode, you can shell into the container now, hit enter to let container stop: ' 
  fi  
}

function main() {
  process_args "$@"

  if [ ! -z "$TARGET_NETWORK_RPC_URL" ] && [ ! -z "$TARGET_NETWORK" ]; then
      echo "Invalid TargetNetwork config, must be TargetNetwork=standalone|futurenet or TargetNetworkRPCURL, aborting test ..." >&2
      exit 1
  fi  

  if [ -z "$TARGET_NETWORK_RPC_URL" ] && [ "$TARGET_NETWORK" != "standalone" ] && [ "$TARGET_NETWORK" != "futurenet" && ]; then
      echo "Invalid TargetNetwork, must be one of standalone or futurenet, aborting test ..." >&2
      exit 1
  fi  

  if [ -z "$TARGET_NETWORK_RPC_URL" ]; then

    TARGET_NETWORK_RPC_URL=http://localhost:8000/soroban/rpc
    print_screen_output "starting target stack on $TARGET_NETWORK with following server versions:"
    print_screen_output "  CORE VERSION=$(stellar-core version 2>/dev/null || echo "n/a")"
    print_screen_output "  HORIZON VERSION=$(stellar-horizon version 2>/dev/null || echo "n/a")"
    print_screen_output "  SOROBAN RPC VERSION=$(stellar-soroban-rpc version 2>/dev/null || echo "n/a")"
      
    if [ "$TARGET_NETWORK" = "standalone" ]; then
        ARTIFICIAL_ACCELERATE=--enable-core-artificially-accelerate-time-for-testing
    fi          

    # using stdbuf to eliminate any buffering between pipe,   
    stdbuf -o0 /start --$TARGET_NETWORK --enable-soroban-rpc $ARTIFICIAL_ACCELERATE --logs 2>&1 | stdbuf -i0 -o0 tee -a -i $LOG_FILE &
    horizon_status
    soroban_rpc_status 
  else
    soroban_rpc_status     
  fi
  
  print_screen_output "  RUST_TOOLCHAIN_VERSION=$(rustc --version 2>/dev/null || echo"n/a" )"
  print_screen_output "  SOROBAN_CLI_CRATE_VERSION=$(soroban version 2>/dev/null || echo "n/a" )"
  print_screen_output "  SOROBAN_EXAMPLES_GIT_HASH=$SOROBAN_EXAMPLES_GIT_HASH"
  print_screen_output "  SOROBAN_EXAMPLES_REPO_URL=$SOROBAN_EXAMPLES_REPO_URL"
  print_screen_output "  TARGET_NETWORK=$TARGET_NETWORK"
  print_screen_output "  TARGET_NETWORK_PASSPHRASE=$TARGET_NETWORK_PASSPHRASE"
  print_screen_output "  TARGET_NETWORK_SECRET_KEY=$TARGET_NETWORK_SECRET_KEY"
  print_screen_output "  TARGET_NETWORK_PUBLIC_KEY=$TARGET_NETWORK_PUBLIC_KEY"
  print_screen_output "  TARGET_NETWORK_RPC_URL=$TARGET_NETWORK_RPC_URL"
  print_screen_output "  TEST_FILTER=${TEST_FILTER}"
  print_screen_output "Tests can now begin ..." 

  cd /opt/test/bin

  export SorobanExamplesGitHash=${SOROBAN_EXAMPLES_GIT_HASH}
  export SorobanExamplesRepoURL=${SOROBAN_EXAMPLES_REPO_URL}
  export TargetNetworkPassPhrase="${TARGET_NETWORK_PASSPHRASE}"
  export TargetNetworkSecretKey=${TARGET_NETWORK_SECRET_KEY}
  export TargetNetworkPublicKey=${TARGET_NETWORK_PUBLIC_KEY}
  export TargetNetworkRPCURL=${TARGET_NETWORK_RPC_URL}
  export VerboseOutput=${VERBOSE_OUTPUT}

  for file in ./*;
  do
    if [ "$CANCELLED" = "true" ]; then
        break
    fi

    if [[ "$file" =~ ^.*\.feature$ ]]; then
        continue
    fi
    # these bin files were compiled from go feature tests in the Dockerfile during image build
    print_screen_output "Running test binary ${file} ... "
    ${file} -test.v ${TEST_FILTER} 2>&1 | tee -a $LOG_FILE
  done
}

function process_args() {
  while [[ -n "$1" ]]; do
    ARG="$1"
    shift

    case "${ARG}" in
    --DebugMode)
      DEBUG_MODE="$1"
      shift
      ;;    
    --SorobanExamplesGitHash)
      SOROBAN_EXAMPLES_GIT_HASH="$1"
      shift
      ;;     
    --SorobanExamplesRepoURL)
      SOROBAN_EXAMPLES_REPO_URL="$1"
      shift
      ;;   
    --TestFilter)
      TEST_FILTER="-test.run ""$1"""
      shift
      ;;     
    --VerboseOutput)
      VERBOSE_OUTPUT="$1"
      shift
      ;;  
    --TargetNetwork)
      TARGET_NETWORK="$1"
      shift
      ;;  
    --TargetNetworkPassphrase) 
      TARGET_NETWORK_PASSPHRASE="$1"
      shift
      ;;    
    --TargetNetworkTestAccountSecret) 
      TARGET_NETWORK_SECRET_KEY="$1"
      shift
      ;;    
    --TargetNetworkTestAccountPublic) 
      TARGET_NETWORK_PUBLIC_KEY="$1"
      shift
      ;;       
    --TargetNetworkRPCURL) 
      TARGET_NETWORK_RPC_URL="$1"
      shift
      ;;            
    *)
    esac
  done

  if [ -z "$TARGET_NETWORK_RPC_URL" ] && [ -z "$TARGET_NETWORK" ]; then
      TARGET_NETWORK=standalone
  fi 
}

function soroban_rpc_status () {
  print_screen_output "waiting for soroban rpc to report ready state..." 
  COUNTER=1
  while ! $(curl --silent --location --request POST 'http://localhost:8000/soroban/rpc' \
    --header 'Content-Type: application/json' \
    --data-raw '{
        "jsonrpc": "2.0",
        "id": 10235,
        "method": "getHealth"
        
    }' | jq --exit-status '.result.status == "healthy"' 2>/dev/null | grep -o true || echo false ); 
  do
    if [ $(expr $COUNTER % 12) -eq 0 ]; then 
      print_screen_output "waited $(expr $COUNTER / 12) minutes for soroban rpc to report ready state..." 
    fi
    COUNTER=$[$COUNTER +1]    
    sleep 5
  done 
  print_screen_output "soroban rpc reported ready status, the service can be used by tools/cli now ..." 
}

function horizon_status () {
  COUNTER=1
  print_screen_output "waiting for horizon ingestion to be caught up to network current ledger..." 
  while ! $(curl --silent --location --request GET 'http://localhost:8000' | \
    jq --exit-status '.core_latest_ledger > 5 and .history_latest_ledger > 5 and (.core_latest_ledger - .history_latest_ledger) < 5' 2>/dev/null | \
    grep -o true || echo false ); 
  do
    if [ $(expr $COUNTER % 12) -eq 0 ]; then 
      print_screen_output "waited $(expr $COUNTER / 12) minutes for horizon ingestion to be caught up to network current ledger..." 
    fi 
    COUNTER=$[$COUNTER +1] 
    sleep 5
  done 
  print_screen_output "horizon ingestion is caught up to network current ledger ..." 
}

main "$@"
