name: Systems test workflow

on:
  workflow_call:
    inputs:
      # the pre-compiled image to use of quickstart, or the git ref to build
      # from source.
      # TODO: allow other versions
#      SYSTEM_TEST_QUICKSTART_IMAGE:
#        required: true
#        type: string
      # TODO allow building from source
      # SYSTEM_TEST_QUICKSTART_GIT_REF: "https://github.com/stellar/quickstart.git#master"


      # the version of components built in quickstart. only used if quickstart
      # is configured above to build from source.
      # SYSTEM_TEST_PROTOCOL_VERSION_DEFAULT: 21
      # SYSTEM_TEST_RS_XDR_GIT_REF: v21.0.1
      # SYSTEM_TEST_CORE_IMAGE:
      # SYSTEM_TEST_CORE_GIT_REF: https://github.com/stellar/stellar-core.git#v21.0.0rc1
      # SYSTEM_TEST_CORE_COMPILE_CONFIGURE_FLAGS: "--disable-tests"
      # SYSTEM_TEST_SOROBAN_RPC_REF: https://github.com/stellar/soroban-rpc.git#v21.0.1

      # the soroban CLI source code to compile and run from system test
      # refers to checked out source of current GitHub ref context or branch
      SOROBAN_CLI_REF:
        type: string
      SOROBAN_CLI_BRANCH:
        type: string
        default: main

      # TODO: do we still want it?
      # sets the version of rust toolchain that will be pre-installed in the
      # test runtime environment, tests invoke rustc/cargo
#      SYSTEM_TEST_RUST_TOOLCHAIN_VERSION:
#        required: true
#        type: string
#        default: stable


      # set the version of js-stellar-sdk to use, need to choose one of either
      # resolution options, using npm release or a gh ref:
      # option #1, set the version of stellar-sdk based on a npm release version
      JS_STELLAR_SDK_NPM_VERSION:
        type: string
        default: 12.2.0

      # TODO allow other options
      # option #2, set the version of stellar-sdk used as a ref to a gh repo if
      # a value is set on SYSTEM_TEST_JS_STELLAR_SDK_GH_REPO, it takes
      # precedence over any SYSTEM_TEST_JS_STELLAR_SDK_NPM_VERSION
      # SYSTEM_TEST_JS_STELLAR_SDK_GH_REPO:
      # SYSTEM_TEST_JS_STELLAR_SDK_GH_REF:

      # triggers system test to log out details from quickstart's logs and test steps
      # TODO
      #VERBOSE_OUTPUT:
       # type: boolean
       # default: true

      # TODO
      # the soroban test cases will compile various contracts from the examples repo
      # SOROBAN_EXAMPLES_GIT_HASH:
        #type: string

jobs:
  systems-test:
    # TODO: allow other runners
    runs-on: ubuntu-latest
    # TODO: allow other versions
    services:
      rpc:
        image: stellar/quickstart:testing
        ports:
          - 8000:8000
        env:
          ENABLE_LOGS: true
          NETWORK: local
          ENABLE_SOROBAN_RPC: true
        options: >-
          --health-cmd "curl --no-progress-meter --fail-with-body -X POST \"http://localhost:8000/rpc\" -H 'Content-Type: application/json' -d '{\"jsonrpc\":\"2.0\",\"id\":8675309,\"method\":\"getNetwork\"}' && curl --no-progress-meter \"http://localhost:8000/friendbot\" | grep '\"invalid_field\": \"addr\"'"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 50
    steps:
      - uses: actions/checkout@v4
      - uses: stellar/actions/rust-cache@main
      - run: rustup update
      - run: cargo install --git https://github.com/stellar/stellar-cli --rev ${{ inputs.SOROBAN_CLI_REF }}
        if: ${{ inputs.SOROBAN_CLI_REF != '' }}
      - run: cargo install --git https://github.com/stellar/stellar-cli --branch ${{ inputs.SOROBAN_CLI_BRANCH }}
        if: ${{ inputs.SOROBAN_CLI_REF == '' }}
      - run: sudo apt update && sudo apt install -y libudev-dev libdbus-1-dev
      - run: go mod download
      - run: |
          go test -c -o ./bin/dapp_develop_test.bin ./features/dapp_develop/...
          cp features/dapp_develop/dapp_develop.feature ./bin
          cp features/dapp_develop/soroban_config.exp ./bin
          cp invoke.ts ./bin
          cp events.ts ./bin
      - run: npm install -g ts-node
      - run: yarn add "@stellar/stellar-sdk@${{ inputs.JS_STELLAR_SDK_NPM_VERSION }}" --network-concurrency 1
      # TODO: get rid of the script
      - run: ./start-ci
