name: Systems test

on:
  push:
    branches: [main, release/**]
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_protected == 'true' && github.sha || github.ref }}
  cancel-in-progress: true

jobs:
  systems-test:
    name: System tests
    uses: ./.github/workflows/test.yml
